version: "3.8"

x-airflow-common: &airflow-common
  image: formation/steampowered:1.0
  command: celery worker
  environment:
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:${AIRFLOW_PG_PASSWORD}@postgres/airflow
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${AIRFLOW_PG_PASSWORD}@postgres/airflow
    STEAMPOWERED__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://steampowered:${STEAMPOWERED_PG_PASSWORD}@postgres/steampowered
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/src
    - ./config/airflow.cfg:/opt/airflow/airflow.cfg

services:
  worker-2:
    <<: *airflow-common
    networks:
      steam-satcli:
        aliases:
          - worker-2
          
  worker-3:
    <<: *airflow-common
    networks:
      steam-satcli:
        aliases:
          - worker-3

networks:
  steam-satcli:
    driver: bridge
